- hosts: all
  name: mini project
  become: true
  tasks:
    - name: httpd
      yum:
        name: httpd
        state: present
    - name: start service
      service:
        name: httpd
        state: started
    - name: install git 
      yum:
        name: git
        state: present
    - name: git repo
      git:
        repo: https://github.com/prajju1509/html-css-repo.git
        dest: /var/www/html/
    - name: apache2
      apt:
        name: apache2
        state: present
    - name: start service
      service:
        name: apache2
        state: started
    - name: install git
      apt:
        name: git
        state: present
    - name: git repo
      git:
        repo: https://github.com/prajju1509/html-css-repo.git
        dest: /var/www/html/
